name: Update README

on:
  release:
    types: [created]

env:
  REPO_NAME: ${{ env.GITHUB_REPOSITORY }}

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout .github repository
        uses: actions/checkout@v2
        with:
          ref: master
          repository: freek-organization/.github
          path: .github

      - name: Install dependencies
        run: |
          npm install @octokit/rest

      - name: Get latest release
        id: latest_release
        run: |
          const octokit = require('@octokit/rest')()
          const { data: releases } = await octokit.repos.listReleases({ owner: '${GITHUB_ACTOR}', repo: '${{ env.REPO_NAME }}' })
          const latestRelease = releases[0].tag_name
          console.log(`Latest release: ${latestRelease}`)
          env.LATEST_TAG = latestRelease

      - name: Update README
        if: steps.latest_release.outputs.LATEST_TAG
        env:
          REPO_NAME: ${{ env.REPO_NAME }}
          LATEST_TAG: ${{ env.LATEST_TAG }}
        uses: ./.github/workflows/update_readme.yml
        with:
          client_payload: '{"repo_name": "${{ env.REPO_NAME }}", "latest_tag": "${{ env.LATEST_TAG }}"}'
